In [4]:
import pandas as pd

reviews = pd.read_csv("winemag-data-130k-v2.csv", index_col=0)

print("Setup complete.")

Setup complete.

In [5]:
reviews = pd.read_csv("winemag-data_first150k.csv", index_col=0)

In [6]:
renamed = reviews.rename(columns={"region_1": "region", "region_2": "locale"})

renamed

,country,description,designation,points,price,province,region,locale,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [9]:
reindexed = reviews.rename_axis("wines")

reindexed

,country,description,designation,points,price,province,region_1,region_2,variety,winery
wines,,,,,,,,,,
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [21]:
gaming_products = pd.read_csv("gaming.csv")
movie_products = pd.read_csv("movies.csv")

In [22]:
gaming_products["subreddit"] = "r/gaming"
movie_products["subreddit"] = "r/movies"

In [26]:
combined_products = pd.concat([gaming_products, movie_products])  # listen kombinieren

combined_products

,name,category,amazon_link,total_mentions,subreddit_mentions,subreddit
0,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4,r/gaming
1,Raspberry PI 3 Model B 1.2GHz 64-bit quad-core...,Electronics,https://www.amazon.com/Raspberry-Model-A1-2GHz...,19.0,3,r/gaming
2,CanaKit 5V 2.5A Raspberry Pi 3 Power Supply / ...,Electronics,https://www.amazon.com/CanaKit-Raspberry-Suppl...,7.0,3,r/gaming
3,Panasonic K-KJ17MCA4BA Advanced Individual Cel...,Electronics,https://www.amazon.com/Panasonic-Advanced-Indi...,29.0,2,r/gaming
4,Mayflash GameCube Controller Adapter for Wii U...,Electronics,https://www.amazon.com/GameCube-Controller-Ada...,24.0,2,r/gaming
...,...,...,...,...,...,...
298,Welcome to Night Vale CD: A Novel,Books,https://www.amazon.com/Welcome-Night-Vale-CD-N...,1.0,1,r/movies
299,Ran (StudioCanal Collection) [Blu-ray],Movies & TV,https://www.amazon.com/StudioCanal-Collection-...,1.0,1,r/movies
300,The Art of John Alvin,Books,https://www.amazon.com/Art-John-Alvin-Andrea/d...,1.0,1,r/movies
301,Apocalypto [Blu-ray],Movies & TV,https://www.amazon.com/Apocalypto-Blu-ray-Rudy...,1.0,1,r/movies
302,Cinelinx: A Card Game for People Who Love Movi...,Toys & Games,https://www.amazon.com/Cinelinx-Card-Game-Peop...,1.0,1,r/movies

In [27]:
import numpy as np

# Random-Spalte mit den Werten 1, 2 oder 3 für gaming_products erstellen
gaming_products["random_value"] = np.random.choice([1, 2, 3], size=len(gaming_products))

# Random-Spalte mit den Werten 1, 2 oder 3 für movie_products erstellen
movie_products["random_value"] = np.random.choice([1, 2, 3], size=len(movie_products))

In [28]:
gaming_products
movie_products

,name,category,amazon_link,total_mentions,subreddit_mentions,subreddit,random_value
0,Marvel Cinematic Universe: Phase One - Avenger...,Movies & TV,https://www.amazon.com/Marvel-Cinematic-Univer...,4.0,3,r/movies,3
1,On Stranger Tides,Books,https://www.amazon.com/Stranger-Tides-Tim-Powe...,3.0,3,r/movies,2
2,"Superintelligence: Paths, Dangers, Strategies",Books,https://www.amazon.com/Superintelligence-Dange...,7.0,2,r/movies,2
3,The Secret History of Star Wars,Books,https://www.amazon.com/Secret-History-Star-War...,4.0,2,r/movies,3
4,2D Glasses 4 Pack - Turns 3D movies back into ...,Electronics,https://www.amazon.com/gp/product/B00K9E7GCC,3.0,2,r/movies,1
...,...,...,...,...,...,...,...
298,Welcome to Night Vale CD: A Novel,Books,https://www.amazon.com/Welcome-Night-Vale-CD-N...,1.0,1,r/movies,2
299,Ran (StudioCanal Collection) [Blu-ray],Movies & TV,https://www.amazon.com/StudioCanal-Collection-...,1.0,1,r/movies,2
300,The Art of John Alvin,Books,https://www.amazon.com/Art-John-Alvin-Andrea/d...,1.0,1,r/movies,1
301,Apocalypto [Blu-ray],Movies & TV,https://www.amazon.com/Apocalypto-Blu-ray-Rudy...,1.0,1,r/movies,3
302,Cinelinx: A Card Game for People Who Love Movi...,Toys & Games,https://www.amazon.com/Cinelinx-Card-Game-Peop...,1.0,1,r/movies,2

In [30]:
# mit movie und gaming aufgabe 4 gemacht da csv von powerlifting nicht gefunden zum runterladen
left = gaming_products.set_index("random_value")
right = movie_products.set_index("random_value")

powerlifting_combined = left.join(right, lsuffix="_gaming", rsuffix="_movie")

powerlifting_combined

,name_gaming,category_gaming,amazon_link_gaming,total_mentions_gaming,subreddit_mentions_gaming,subreddit_gaming,name_movie,category_movie,amazon_link_movie,total_mentions_movie,subreddit_mentions_movie,subreddit_movie
random_value,,,,,,,,,,,,
2,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4,r/gaming,On Stranger Tides,Books,https://www.amazon.com/Stranger-Tides-Tim-Powe...,3.0,3,r/movies
2,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4,r/gaming,"Superintelligence: Paths, Dangers, Strategies",Books,https://www.amazon.com/Superintelligence-Dange...,7.0,2,r/movies
2,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4,r/gaming,Hank Green's 2D-Glasses: Turns 3D movies back ...,Electronics,https://www.amazon.com/gp/product/B004X4L1UC,3.0,2,r/movies
2,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4,r/gaming,"Questioning Collapse: Human Resilience, Ecolog...",Books,https://www.amazon.com/Questioning-Collapse-Re...,NaN,1,r/movies
2,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4,r/gaming,Thrustmaster Hotas Warthog Joystick,Electronics,https://www.amazon.com/Thrustmaster-Hotas-Wart...,7.0,1,r/movies
...,...,...,...,...,...,...,...,...,...,...,...,...
2,Project Arcade: Build Your Own Arcade Machine.,Books,https://www.amazon.com/Project-Arcade-Build-Yo...,1.0,1,r/gaming,Who Wacked Roger Rabbit?,Books,https://www.amazon.com/Wacked-Roger-Rabbit-Gar...,1.0,1,r/movies
2,Project Arcade: Build Your Own Arcade Machine.,Books,https://www.amazon.com/Project-Arcade-Build-Yo...,1.0,1,r/gaming,Troll 2 (The 20th Anniversary Nilbog Edition) ...,Movies & TV,https://www.amazon.com/dp/B003ZD9E24,1.0,1,r/movies
2,Project Arcade: Build Your Own Arcade Machine.,Books,https://www.amazon.com/Project-Arcade-Build-Yo...,1.0,1,r/gaming,Welcome to Night Vale CD: A Novel,Books,https://www.amazon.com/Welcome-Night-Vale-CD-N...,1.0,1,r/movies
2,Project Arcade: Build Your Own Arcade Machine.,Books,https://www.amazon.com/Project-Arcade-Build-Yo...,1.0,1,r/gaming,Ran (StudioCanal Collection) [Blu-ray],Movies & TV,https://www.amazon.com/StudioCanal-Collection-...,1.0,1,r/movies
2,Project Arcade: Build Your Own Arcade Machine.,Books,https://www.amazon.com/Project-Arcade-Build-Yo...,1.0,1,r/gaming,Cinelinx: A Card Game for People Who Love Movi...,Toys & Games,https://www.amazon.com/Cinelinx-Card-Game-Peop...,1.0,1,r/movies